# @format

# global hooks
# supported keys:
# before_setup: Array of commands before all files are processd
# after_setup: Array of commands after all files are processed
# after setup
hooks:
# Files as array
# supported keys:
#   dst: filename to be saved
#   before_setup: Array of commands to executed before setup
#   after_setup: array of commands after setup
#   force_override: should override existing file
files:
  vim:
    src: '~/.vimrc':
    dst: 'vimrc'
    before_setup:
      - 'sh ./installer.sh ~/.vim/bundles'
  nvim:
    src: '~/.config/nvim/init.vim':
    dst: nvim_init.vim
    before_setup:
      - 'sh ./installer.sh ~/.nvim/bundles'
  zsh:
    src: '~/.zshrc':
    dst: 'zshrc'
    before_setup:
      - 'wget -O ~/antigen.zsh git.io/antigen'
      - 'sh ./install_starship.sh'
  tmux:
    src:'~/.tmux.conf.local':
    dst: tmux.conf.local
    before_setup:
      - git clone https://github.com/gpakosz/.tmux.git ~/.tmux
      - 'ln -s -f .tmux/.tmux.conf ~/.tmux.conf'
      
      
