# This is a basic workflow to help you get started with Actions

name: Build & Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: v*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Relaase Version'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it\
      - name: "Checkout repo"
        uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v4.6.0
        with:
            python-version: ~3.8.0
      
      - name: Setup Poetry
        run: python3 -m pip install poetry
    
      - name: Install deps
        run: python3 -m poetry install

      - name: Run tests
        run: python3 -m poetry run pytest
      
      - name: Build package
        run: python3 -m poetry build
      
      - name: Add to release
        if: ${{ github.event.inputs.release_version }} 
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.inputs.release_version }}
          tag: ${{ format('v{0}', github.event.inputs.release_version )}}
          artifacts: "dist/*"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      
      - name: Add to release by Tag
        if: startsWith(github.ref, 'ref/tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          
      - name: "Upload to pypi"
        run: python3 -m poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
        
